{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
{{- end }}

